import express from "express";
import { addAsset, getAllAssets, removePassengerFromAsset, addMultiplePassengersToAsset, updateAsset, deleteAsset, getAvailableAssets} from "../controllers/assetController.js";
const router = express.Router();
router.get("/available", getAvailableAssets);
router.post("/add", addAsset);
router.get("/all", getAllAssets);
router.post("/:id", updateAsset);
router.delete("/:id", deleteAsset);
router.post("/:id/remove-passenger", removePassengerFromAsset);
router.post("/:id/addMultiplePassengers", addMultiplePassengersToAsset);
export default router;